language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t diogoafg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diogoafg/react-test npm test

after_success:
  - docker build -t diogoafg/multi-client ./client
  - docker build -t diogoafg/multi-nginx ./nginx
  - docker build -t diogoafg/multi-server ./server
  - docker build -t diogoafg/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push diogoafg/multi-client:latest
  - docker push diogoafg/multi-nginx:latest
  - docker push diogoafg/multi-server:latest
  - docker push diogoafg/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-438093953394"
  bucket_path: "docker-multi"
  on:
    branch: develop
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY